### ISSUE TITLE
SSH Agent integration

### ISSUE THREAD

**Issue by hugoduncan** [hierynomus/sshj#33] opened 2011-09-23 16:24 UTC
Is there any interest in providing ssh agent integration, similar to that provided by Mina? This requires some sort of native library to access the unix socket (Mina use the apache runtime I believe), so would probably need to be made optional.

Any thoughts?

**Comment by hierynomus** [comment] 2015-01-09 14:53
This seems to be solved? Correct, if so, closing it soon...

**Comment by dkocher** [comment] 2015-04-21 07:46
I can confirm that the combination with the jsch-agent-proxy is working. I propose to close this issue.

**Comment by hierynomus** [comment] 2015-04-21 08:52
Closing :)

**Closed by hierynomus** 2015-04-21 08:52 UTC
Labels: feature
