### ISSUE TITLE
et.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint ...

### ISSUE THREAD

**Issue by mvysny** [hierynomus/sshj#358] opened 2017-09-12 17:41 UTC
I'm using sshj 0.22.0; the following code fails for me:

```
        val ssh = SSHClient()
        ssh.loadKnownHosts()
        ssh.connect("my.server")
```

The log output is:
```
20:34:43.940 [main] INFO net.schmizz.sshj.transport.random.BouncyCastleRandom - Generating random seed from SecureRandom.
20:34:43.943 [main] DEBUG net.schmizz.sshj.transport.random.BouncyCastleRandom - Creating random seed took 0 ms
20:34:44.008 [main] DEBUG net.schmizz.sshj.DefaultConfig - Available cipher factories: [net.schmizz.sshj.transport.cipher.AES128CTR$Factory@402a079c, net.schmizz.sshj.transport.cipher.AES192CTR$Factory@59ec2012, net.schmizz.sshj.transport.cipher.AES256CTR$Factory@4cf777e8, net.schmizz.sshj.transport.cipher.AES128CBC$Factory@2f686d1f, net.schmizz.sshj.transport.cipher.AES192CBC$Factory@3fee9989, net.schmizz.sshj.transport.cipher.AES256CBC$Factory@73ad2d6, net.schmizz.sshj.transport.cipher.TripleDESCBC$Factory@7085bdee, net.schmizz.sshj.transport.cipher.BlowfishCBC$Factory@1ce92674, blowfish-ctr, cast128-cbc, cast128-ctr, idea-cbc, idea-ctr, serpent128-cbc, serpent128-ctr, serpent192-cbc, serpent192-ctr, serpent256-cbc, serpent256-ctr, 3des-ctr, twofish128-cbc, twofish128-ctr, twofish192-cbc, twofish192-ctr, twofish256-cbc, twofish256-ctr, twofish-cbc, arcfour, arcfour128, arcfour256]
20:34:44.042 [main] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [-72, 47, -123, 101, 10, 62, 23, -24, 76, -119, -21, 126, -28, 89, 101, -67, -28, 19, -90, -62, 90, -55, -99, 43, 48, 54, -37, -13, 113, -97, -52, -65]
y: [117, -6, -34, -15, -94, 107, -121, -47, 80, -96, -107, -115, 114, -85, 43, 95, -122, 30, 46, -81, -20, 44, -62, 124, -38, 78, 118, 109, 114, 68, -115, -52]
20:34:44.193 [main] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [-55, -55, -14, -29, -8, 28, -111, -54, 106, 110, 100, 111, 46, -65, -11, -127, -31, 5, -64, 91, 101, 104, -56, -84, 21, -83, 27, -33, 119, 17, 26, 48]
y: [-67, -52, -10, -90, 112, 72, 86, 75, -51, 63, -78, -32, 102, -23, -88, -31, -42, -62, -110, 118, -20, 16, -34, -109, -91, -75, 14, -73, 35, -37, -59, -34]
20:34:44.194 [main] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [-55, -55, -14, -29, -8, 28, -111, -54, 106, 110, 100, 111, 46, -65, -11, -127, -31, 5, -64, 91, 101, 104, -56, -84, 21, -83, 27, -33, 119, 17, 26, 48]
y: [-67, -52, -10, -90, 112, 72, 86, 75, -51, 63, -78, -32, 102, -23, -88, -31, -42, -62, -110, 118, -20, 16, -34, -109, -91, -75, 14, -73, 35, -37, -59, -34]
20:34:44.194 [main] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [-55, -55, -14, -29, -8, 28, -111, -54, 106, 110, 100, 111, 46, -65, -11, -127, -31, 5, -64, 91, 101, 104, -56, -84, 21, -83, 27, -33, 119, 17, 26, 48]
y: [-67, -52, -10, -90, 112, 72, 86, 75, -51, 63, -78, -32, 102, -23, -88, -31, -42, -62, -110, 118, -20, 16, -34, -109, -91, -75, 14, -73, 35, -37, -59, -34]
20:34:44.195 [main] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [28, -84, 90, -128, 0, 98, 61, -104, 90, -49, 79, 89, 21, 21, 23, -64, -3, 46, 117, -59, 0, -105, 39, 5, -66, 87, -62, 89, 57, -126, 6, -116]
y: [-65, 108, -82, -12, 38, 101, -34, -37, 109, -86, 55, -123, 6, 104, -120, -102, 32, -74, -26, 3, -3, -98, -53, -91, 121, 110, 126, -33, 23, 26, 111, 17]
20:34:44.196 [main] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [28, -84, 90, -128, 0, 98, 61, -104, 90, -49, 79, 89, 21, 21, 23, -64, -3, 46, 117, -59, 0, -105, 39, 5, -66, 87, -62, 89, 57, -126, 6, -116]
y: [-65, 108, -82, -12, 38, 101, -34, -37, 109, -86, 55, -123, 6, 104, -120, -102, 32, -74, -26, 3, -3, -98, -53, -91, 121, 110, 126, -33, 23, 26, 111, 17]
20:34:44.196 [main] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [-72, 47, -123, 101, 10, 62, 23, -24, 76, -119, -21, 126, -28, 89, 101, -67, -28, 19, -90, -62, 90, -55, -99, 43, 48, 54, -37, -13, 113, -97, -52, -65]
y: [117, -6, -34, -15, -94, 107, -121, -47, 80, -96, -107, -115, 114, -85, 43, 95, -122, 30, 46, -81, -20, 44, -62, 124, -38, 78, 118, 109, 114, 68, -115, -52]
20:34:44.288 [main] INFO net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-SSHJ_0.22.0
20:34:44.350 [main] INFO net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-OpenSSH_6.0p1 Debian-4+deb7u6
20:34:44.351 [main] DEBUG net.schmizz.concurrent.Promise - Setting <<kex done>> to `null`
20:34:44.351 [main] DEBUG net.schmizz.sshj.transport.KeyExchanger - Sending SSH_MSG_KEXINIT
20:34:44.355 [main] DEBUG net.schmizz.concurrent.Promise - Setting <<kexinit sent>> to `SOME`
20:34:44.356 [main] DEBUG net.schmizz.concurrent.Promise - Awaiting <<kex done>>
20:34:44.404 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received SSH_MSG_KEXINIT
20:34:44.405 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Negotiated algorithms: [ kex=diffie-hellman-group-exchange-sha256; sig=ecdsa-sha2-nistp256; c2sCipher=aes128-ctr; s2cCipher=aes128-ctr; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none ]
20:34:44.417 [reader] DEBUG net.schmizz.sshj.transport.kex.DHGexSHA256 - Sending KEX_DH_GEX_REQUEST
20:34:44.465 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received kex followup data
20:34:44.465 [reader] DEBUG net.schmizz.sshj.transport.kex.DHGexSHA256 - Got message KEXDH_31
20:34:44.466 [reader] DEBUG net.schmizz.sshj.transport.kex.DHGexSHA256 - Received server p bitlength 2048
20:34:44.531 [reader] DEBUG net.schmizz.sshj.transport.kex.DHGexSHA256 - Sending KEX_DH_GEX_INIT
20:34:44.592 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received kex followup data
20:34:44.593 [reader] DEBUG net.schmizz.sshj.transport.kex.DHGexSHA256 - Got message KEX_DH_GEX_REPLY
20:34:44.593 [reader] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [-88, -11, -26, 69, -85, 2, -118, 79, 92, 4, 18, -44, 127, 90, 74, 19, -128, -98, -15, 28, -112, -81, -55, 67, -88, -23, 6, -94, 80, -106, 75, -16]
y: [-3, -77, -104, 57, 6, -63, -30, 49, 62, -91, -31, -87, 90, 19, -80, -8, -87, -45, 24, 8, -46, 105, 96, 62, 74, -7, -91, 73, 97, -104, 57, -99]
20:34:44.675 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Trying to verify host key with net.schmizz.sshj.transport.verification.OpenSSHKnownHosts@321cb9bc
20:34:44.683 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Trying to verify host key with net.schmizz.sshj.transport.verification.OpenSSHKnownHosts@403b9b05
20:34:44.686 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `98:5a:76:cb:99:77:f8:dc:ad:80:bc:7c:9c:e6:1c:f0` for `my.server` on port 22
net.schmizz.sshj.transport.TransportException: Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `98:5a:76:cb:99:77:f8:dc:ad:80:bc:7c:9c:e6:1c:f0` for `my.server` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:205)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:359)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
20:34:44.687 [reader] INFO net.schmizz.sshj.transport.TransportImpl - Disconnected - HOST_KEY_NOT_VERIFIABLE
20:34:44.687 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Got notified of net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `98:5a:76:cb:99:77:f8:dc:ad:80:bc:7c:9c:e6:1c:f0` for `my.server` on port 22
20:34:44.687 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl$NullService - Notified of net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `98:5a:76:cb:99:77:f8:dc:ad:80:bc:7c:9c:e6:1c:f0` for `my.server` on port 22
20:34:44.687 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl - Setting active service to null-service
20:34:44.687 [main] ERROR net.schmizz.concurrent.Promise - <<kex done>> woke to: net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `98:5a:76:cb:99:77:f8:dc:ad:80:bc:7c:9c:e6:1c:f0` for `my.server` on port 22
20:34:44.687 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl - Sending SSH_MSG_DISCONNECT: reason=[HOST_KEY_NOT_VERIFIABLE], msg=[Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `98:5a:76:cb:99:77:f8:dc:ad:80:bc:7c:9c:e6:1c:f0` for `myserver` on port 22]
20:34:44.688 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<transport close>> to `SOME`
20:34:44.688 [reader] DEBUG net.schmizz.sshj.transport.Reader - Stopping
net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `98:5a:76:cb:99:77:f8:dc:ad:80:bc:7c:9c:e6:1c:f0` for `myserver` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:205)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:359)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
```

I can ssh from my Linux box to the machine without any issues, so the known_hosts file is fine and is in the following format:
```
|1|foo...|foo...= ecdsa-sha2-nistp256
```

NB: it is extremely ugly to throw an exception with a stacktrace coming from a different thread since it is impossible to see where exactly in my code the SSH connection failed! Please rewrap the exception in sshj so that both the original thread stacktrace and `main` thread stacktrace is visible.

**Comment by mvysny** [comment] 2017-09-12 17:46
I can see that this issue is the same as #318, however:
1. I am using openjdk8 and thus the unlimited cryptography policy
2. I am loading known_hosts
3. For security reasons, using `PromiscuousVerifier` is out of the question.
Any suggestions please?

**Comment by BigChief45** [comment] 2017-10-04 18:16
I am experiencing the same issue. I can connect no problem using a different client such as WinSCP.

Any ideas?

@hierynomus

**Comment by hierynomus** [comment] 2017-10-04 21:27
Can you try using the latest master? There were some corner case bugs.

**Comment by richbirch** [comment] 2017-11-01 12:15
Latest version (0.23.0) is still giving me this issue. Any found a workaround?

**Comment by KinglyWayne** [comment] 2017-12-26 14:28
Even if I use PromiscuousVerifier, it still does not work (both 0.22.0 and 0.23.0)

`net.schmizz.sshj.transport.TransportException: java.security.spec.InvalidKeySpecException: key spec not recognized
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:33)
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:27)
	at net.schmizz.concurrent.Promise.deliverError(Promise.java:96)
	at net.schmizz.concurrent.Event.deliverError(Event.java:74)
	at net.schmizz.concurrent.ErrorDeliveryUtil.alertEvents(ErrorDeliveryUtil.java:34)
	at net.schmizz.sshj.transport.KeyExchanger.notifyError(KeyExchanger.java:386)
	at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:600)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:67)
Caused by: net.schmizz.sshj.common.SSHException: java.security.spec.InvalidKeySpecException: key spec not recognized
	at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:36)
	at net.schmizz.sshj.common.SSHException$1.chain(SSHException.java:29)
	at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:595)
	... 1 more
Caused by: net.schmizz.sshj.common.SSHRuntimeException: java.security.spec.InvalidKeySpecException: key spec not recognized
	at net.schmizz.sshj.common.Buffer.readPublicKey(Buffer.java:466)
	at net.schmizz.sshj.transport.kex.AbstractDHG.next(AbstractDHG.java:66)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:358)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
Caused by: java.security.GeneralSecurityException: java.security.spec.InvalidKeySpecException: key spec not recognized
	at net.schmizz.sshj.common.ECDSAVariationsAdapter.readPubKeyFromBuffer(ECDSAVariationsAdapter.java:91)
	at net.schmizz.sshj.common.KeyType$3.readPubKeyFromBuffer(KeyType.java:122)
	at net.schmizz.sshj.common.Buffer.readPublicKey(Buffer.java:464)
	... 6 more
Caused by: java.security.spec.InvalidKeySpecException: key spec not recognized
	at org.bouncycastle.jcajce.provider.asymmetric.util.BaseKeyFactorySpi.engineGeneratePublic(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi.engineGeneratePublic(Unknown Source)
	at java.security.KeyFactory.generatePublic(KeyFactory.java:334)
	at net.schmizz.sshj.common.ECDSAVariationsAdapter.readPubKeyFromBuffer(ECDSAVariationsAdapter.java:89)
	... 8 more`

**Comment by KinglyWayne** [comment] 2017-12-26 14:30
debug log is as blew (for sshj 0.23.0)

`2017-12-26 16:28:18 [[ACTIVE] ExecuteThread: '7' for queue: 'weblogic.kernel.Default (self-tuning)'] DEBUG net.schmizz.concurrent.Promise - Awaiting <<kex done>>
2017-12-26 16:28:18 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received SSH_MSG_KEXINIT
2017-12-26 16:28:18 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Negotiated algorithms: [ kex=curve25519-sha256@libssh.org; sig=ecdsa-sha2-nistp256; c2sCipher=aes128-cbc; s2cCipher=aes128-cbc; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none ]
2017-12-26 16:28:18 [reader] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Sending SSH_MSG_KEXDH_INIT
2017-12-26 16:28:18 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received kex followup data
2017-12-26 16:28:18 [reader] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Received SSH_MSG_KEXDH_REPLY
2017-12-26 16:28:18 [reader] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [-40, -36, 87, -100, -33, -100, 97, -84, -67, -117, 72, 60, -84, -82, -119, -57, 29, 108, 118, -46, -11, -12, 93, 80, -76, -109, 77, -46, -19, 71, -106, -123]
y: [85, 103, -55, -98, -23, -96, -10, 84, 52, -6, 79, -30, 83, -116, 1, -38, -85, -45, 61, -128, -114, 42, 55, -38, -114, -25, -33, 16, 15, -69, 9, -58]
2017-12-26 16:28:18 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - java.security.spec.InvalidKeySpecException: key spec not recognized
net.schmizz.sshj.common.SSHRuntimeException: java.security.spec.InvalidKeySpecException: key spec not recognized
	at net.schmizz.sshj.common.Buffer.readPublicKey(Buffer.java:466)
	at net.schmizz.sshj.transport.kex.AbstractDHG.next(AbstractDHG.java:66)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:358)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
Caused by: java.security.GeneralSecurityException: java.security.spec.InvalidKeySpecException: key spec not recognized
	at net.schmizz.sshj.common.ECDSAVariationsAdapter.readPubKeyFromBuffer(ECDSAVariationsAdapter.java:92)
	at net.schmizz.sshj.common.KeyType$3.readPubKeyFromBuffer(KeyType.java:113)
	at net.schmizz.sshj.common.Buffer.readPublicKey(Buffer.java:464)
	... 6 common frames omitted
Caused by: java.security.spec.InvalidKeySpecException: key spec not recognized
	at org.bouncycastle.jcajce.provider.asymmetric.util.BaseKeyFactorySpi.engineGeneratePublic(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi.engineGeneratePublic(Unknown Source)
	at java.security.KeyFactory.generatePublic(KeyFactory.java:334)
	at net.schmizz.sshj.common.ECDSAVariationsAdapter.readPubKeyFromBuffer(ECDSAVariationsAdapter.java:90)
	... 8 common frames omitted
2017-12-26 16:28:18 [reader] INFO  net.schmizz.sshj.transport.TransportImpl - Disconnected - UNKNOWN
2017-12-26 16:28:18 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Got notified of net.schmizz.sshj.common.SSHException: java.security.spec.InvalidKeySpecException: key spec not recognized
2017-12-26 16:28:18 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl$NullService - Notified of net.schmizz.sshj.common.SSHException: java.security.spec.InvalidKeySpecException: key spec not recognized
2017-12-26 16:28:18 [[ACTIVE] ExecuteThread: '7' for queue: 'weblogic.kernel.Default (self-tuning)'] ERROR net.schmizz.concurrent.Promise - <<kex done>> woke to: net.schmizz.sshj.transport.TransportException: java.security.spec.InvalidKeySpecException: key spec not recognized`

**Comment by KinglyWayne** [comment] 2017-12-26 14:34
server is centos7 with OpenSSH_6.6.1
sshj running machine is centos6.8 with oracle jdk +jce enabled
this issue is really driving me crazy
try everthing I can but failed

**Comment by hierynomus** [comment] 2018-01-23 18:59
@chqr @KinglyWayne Could you check with a build from PR #396, to see whether that one fixes the problem?

**Comment by hierynomus** [comment] 2018-01-24 14:55
@mvysny @richbirch Can you also check with a build from #396? I think it should be fixed now.

**Comment by chqr** [comment] 2018-01-24 17:29
@hierynomus Thanks, I'll try #396. I actually suspect this is an issue with BouncyCastle config/initialization in the application we're using. If I simply run [this example](https://github.com/hierynomus/sshj/blob/master/examples/src/main/java/net/schmizz/sshj/examples/Exec.java) against one of our Cent 7 hosts, it works fine.

**Comment by hierynomus** [comment] 2018-03-22 21:52
Ok, cool! Thanks for the update.

**Closed by hierynomus** 2018-03-22 21:52 UTC
