### ISSUE TITLE
README.adoc mentions version 0.25.0 but examples only works by setting 0.19.0 in pom.xml

### ISSUE THREAD

**Issue by texane** [hierynomus/sshj#424] opened 2018-06-08 07:37 UTC
As title says ...

**Comment by IonoclastBrigham** [comment] 2018-06-09 00:58
Duplicate of #416?

**Comment by hierynomus** [comment] 2018-06-19 09:54
@texane Why do the examples not work with a higher version? I cannot find a reason?

**Comment by IonoclastBrigham** [comment] 2018-06-19 17:46
@hierynomus as pointed out in #416, build 0.25.0 was never actually published to maven repo. You can build with version 0.24.0 and older, because those artifacts exist.

**Comment by hierynomus** [comment] 2018-07-24 12:56
I've just released 0.26.0 to Maven central. Should be arriving within the next 2 hours.

**Closed by hierynomus** 2018-07-24 12:56 UTC
